{% set version = "1.9.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-shiny
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/shiny_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/shiny/shiny_{{ version }}.tar.gz
  sha256: d54d9b817dcb877be35ef95525c11abe46ca07c5c719025ba85ac47f2b383486

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-bslib >=0.6.0
    - r-cachem >=1.1.0
    - r-commonmark >=1.7
    - r-crayon
    - r-fastmap >=1.1.1
    - r-fontawesome >=0.4.0
    - r-glue >=1.3.2
    - r-htmltools >=0.5.4
    - r-httpuv >=1.5.2
    - r-jsonlite >=0.9.16
    - r-later >=1.0.0
    - r-lifecycle >=0.2.0
    - r-mime >=0.3
    - r-promises >=1.1.0
    - r-r6 >=2.0
    - r-rlang >=0.4.10
    - r-sourcetools
    - r-withr
    - r-xtable
  run:
    - r-base
    - r-bslib >=0.6.0
    - r-cachem >=1.1.0
    - r-commonmark >=1.7
    - r-crayon
    - r-fastmap >=1.1.1
    - r-fontawesome >=0.4.0
    - r-glue >=1.3.2
    - r-htmltools >=0.5.4
    - r-httpuv >=1.5.2
    - r-jsonlite >=0.9.16
    - r-later >=1.0.0
    - r-lifecycle >=0.2.0
    - r-mime >=0.3
    - r-promises >=1.1.0
    - r-r6 >=2.0
    - r-rlang >=0.4.10
    - r-sourcetools
    - r-withr
    - r-xtable

test:
  commands:
    - $R -e "library('shiny')"           # [not win]
    - "\"%R%\" -e \"library('shiny')\""  # [win]

about:
  license: GPL-3.0-only
  home: https://shiny.rstudio.com/
  summary: Makes it incredibly easy to build interactive web applications with R. Automatic "reactive" binding between inputs and outputs and extensive prebuilt widgets make it possible to build beautiful, responsive, and powerful applications with minimal effort.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - halldc
