{% set version = '1.0.5' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-shiny
  version: {{ version|replace("-", "_") }}

source:
  fn: shiny_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/shiny_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/shiny/shiny_{{ version }}.tar.gz
  sha256: 20e25f3f72f3608a2151663f7836f2e0c6da32683a555d7541063ae7a935fa42

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-r6 >=2.0
    - r-digest
    - r-htmltools >=0.3.5
    - r-httpuv >=1.3.5
    - r-jsonlite >=0.9.16
    - r-mime >=0.3
    - r-sourcetools
    - r-xtable

  run:
    - r-base
    - r-r6 >=2.0
    - r-digest
    - r-htmltools >=0.3.5
    - r-httpuv >=1.3.5
    - r-jsonlite >=0.9.16
    - r-mime >=0.3
    - r-sourcetools
    - r-xtable

test:
  commands:
    - $R -e "library('shiny')"  # [not win]
    - "\"%R%\" -e \"library('shiny')\""  # [win]

about:
  home: http://shiny.rstudio.com
  license: GPL-3
  summary: Makes it incredibly easy to build interactive web applications with R. Automatic "reactive"
    binding between inputs and outputs and extensive prebuilt widgets make it possible
    to build beautiful, responsive, and powerful applications with minimal effort.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
